"""Default bot message templates (ru / uz). Tenants can override via settings.telegram_templates_{lang}."""

TEMPLATES: dict[str, dict[str, str]] = {
    "ru": {
        "choose_language": "🌐 <b>Выберите язык</b> / <b>Tilni tanlang</b>",
        "language_changed": "✅ Язык изменён: <b>{lang_name}</b>",
        "welcome": "👋 <b>Здравствуйте!</b>\n\nДобро пожаловать в бот <b>{company}</b>.\nИспользуйте кнопки ниже 👇",
        "help": "📖 <b>Справка</b>\n\n📝 Регистрация — имя → телефон → фото\n📊 Статус — ваш статус на сегодня\n⏱ Часы — отработано за месяц\n💰 Зарплата — расчёт за месяц\n📄 Табель — календарь месяца\n🚫 Не смогу прийти — заявка на отсутствие\n⏰ Опаздываю — предупредить об опоздании",
        "ask_full_name": "👤 <b>Шаг 1.</b> Введите имя и фамилию\n<i>Например: Иван Иванов</i>",
        "ask_phone": "📞 <b>Шаг 2.</b> Поделитесь номером телефона\n\n📱 Нажмите кнопку <b>«Отправить телефон»</b> внизу",
        "ask_photo": "📸 <b>Шаг 3.</b> Отправьте селфи с чётко видимым лицом",
        "success": "🎉 <b>Поздравляем!</b> Вы зарегистрированы.\n\n👤 {full_name}\n📞 {phone}\n🔢 Таб. №: {employee_number}\n\n✅ Данные добавлены в систему.",
        "success_linked": "🎉 <b>Поздравляем!</b> Telegram привязан к вашей карточке.\n\n👤 {full_name}\n📞 {phone}\n🔢 Таб. №: {employee_number}",
        "already_registered": "✅ Вы уже зарегистрированы:\n<b>{full_name}</b>",
        "not_registered": "⚠️ Вы ещё не зарегистрированы. Нажмите <b>📝 Регистрация</b>.",
        "cancelled": "❌ Действие отменено.",
        "status_registered": "✅ <b>{full_name}</b>\n📅 Сегодня: {today_status}\n\n📆 Месяц: пришёл {worked_days} из {scheduled_days} дн., опозданий {late}, отсутствий {absent}",
        "hours": "⏱ <b>Отработано за {month}:</b> {worked}\n📋 Норма: {scheduled}\n📈 Выполнение: {pct}%",
        "salary": "💰 <b>Расчёт за {month}</b>\n\nНачислено: {earned}\nБонусы: +{bonuses}\nШтрафы: −{fines}\nВыплачено: {paid}\n<b>К выплате: {to_pay}</b>",
        "ask_absence_date": "📅 На какую дату? Отправьте дату в формате <b>ДД.ММ.ГГГГ</b> или нажмите «Сегодня» / «Завтра».",
        "ask_absence_reason": "✍️ Укажите причину отсутствия",
        "ask_absence_photo": "📷 Прикрепите фото (справка и т.п.) или нажмите «Без фото»",
        "absence_sent": "📨 Заявка отправлена на рассмотрение. Вы получите ответ в этом чате.",
        "ask_late_minutes": "⏰ На сколько минут опаздываете? (например: 15)",
        "ask_late_reason": "✍️ Укажите причину опоздания",
        "late_sent": "📨 Сообщение об опоздании отправлено руководителю.",
        "request_approved": "✅ Ваша заявка на {date} <b>принята</b> — штраф не начисляется.\n{comment}",
        "request_rejected": "❌ Ваша заявка на {date} <b>отклонена</b>.\n{comment}",
        "checkin_done": "✅ Отметка <b>{kind}</b> {time} принята.",
        "checkin_not_allowed": "⚠️ Для вашего режима работы отметки через Telegram недоступны — используйте терминал.",
        "invalid_phone": "⚠️ Нажмите кнопку <b>«Отправить телефон»</b> 📱",
        "invalid_photo": "📷 Пожалуйста, отправьте фото.",
        "empty_name": "⚠️ Введите имя.\n<i>Например: Иван или Иван Иванов</i>",
        "new_task": "📋 <b>Новая задача</b>\n\n<b>{title}</b>\n{description}\n\n💰 Бонус: {bonus}\n\nНажмите «Принять», затем отправьте результат (текст или фото).",
        "task_result_ask": "✍️ Отправьте результат по задаче <b>{title}</b>: текст или фото.",
        "task_result_sent": "📨 Результат отправлен на проверку.",
        "task_approved": "✅ Задача <b>{title}</b> подтверждена. Бонус {bonus} начислен.",
        "task_rejected": "❌ Задача <b>{title}</b> отклонена.",
        "feed_pass": "{icon} <b>{full_name}</b>{position}\n🕐 {time} · {direction}{late}",
        "late_alert": "⏰ <b>Опоздание</b>\n👤 {full_name}{department}\n🕐 Пришёл в {time} (график {start}) — опоздание {late}",
        "absent_alert": "🚫 <b>Не пришли</b> ({date}, {count} чел.)\n\n{list}",
        "hr_request": "📨 <b>Заявка: {kind}</b>\n👤 {full_name}{department}\n📅 {date}{late}\n💬 {reason}",
    },
    "uz": {
        "choose_language": "🌐 <b>Tilni tanlang</b> / <b>Выберите язык</b>",
        "language_changed": "✅ Til o'zgartirildi: <b>{lang_name}</b>",
        "welcome": "👋 <b>Assalomu alaykum!</b>\n\n<b>{company}</b> botiga xush kelibsiz.\nQuyidagi tugmalardan foydalaning 👇",
        "help": "📖 <b>Yordam</b>\n\n📝 Ro'yxatdan o'tish — ism → telefon → rasm\n📊 Holat — bugungi holatingiz\n⏱ Soatlar — oy davomida ishlangan\n💰 Maosh — oylik hisob\n📄 Tabel — oy kalendari\n🚫 Kela olmayman — ariza\n⏰ Kechikyapman — ogohlantirish",
        "ask_full_name": "👤 <b>1-qadam.</b> Ism va familiyangizni yozing\n<i>Masalan: Anvar Aliyev</i>",
        "ask_phone": "📞 <b>2-qadam.</b> Telefon raqamingizni ulashing\n\n📱 Pastdagi <b>«Telefonni ulashish»</b> tugmasini bosing",
        "ask_photo": "📸 <b>3-qadam.</b> Yuzingiz aniq ko'rinadigan selfie yuboring",
        "success": "🎉 <b>Tabriklaymiz!</b> Ro'yxatdan o'tdingiz.\n\n👤 {full_name}\n📞 {phone}\n🔢 Tab №: {employee_number}",
        "success_linked": "🎉 <b>Tabriklaymiz!</b> Telegram profilingiz bog'landi.\n\n👤 {full_name}\n📞 {phone}\n🔢 Tab №: {employee_number}",
        "already_registered": "✅ Siz allaqachon ro'yxatdan o'tgansiz:\n<b>{full_name}</b>",
        "not_registered": "⚠️ Siz hali ro'yxatdan o'tmagansiz. <b>📝 Ro'yxatdan o'tish</b> tugmasini bosing.",
        "cancelled": "❌ Bekor qilindi.",
        "status_registered": "✅ <b>{full_name}</b>\n📅 Bugun: {today_status}\n\n📆 Oy: {scheduled_days} kundan {worked_days} keldi, kechikish {late}, kelmagan {absent}",
        "hours": "⏱ <b>{month} uchun ishlangan:</b> {worked}\n📋 Norma: {scheduled}\n📈 Bajarilgan: {pct}%",
        "salary": "💰 <b>{month} hisobi</b>\n\nHisoblangan: {earned}\nBonus: +{bonuses}\nJarima: −{fines}\nTo'langan: {paid}\n<b>To'lanadi: {to_pay}</b>",
        "ask_absence_date": "📅 Qaysi sanaga? <b>KK.OO.YYYY</b> formatida yuboring yoki «Bugun» / «Ertaga» ni bosing.",
        "ask_absence_reason": "✍️ Sababini yozing",
        "ask_absence_photo": "📷 Rasm biriktiring (ma'lumotnoma) yoki «Rasmsiz» ni bosing",
        "absence_sent": "📨 Ariza ko'rib chiqishga yuborildi. Javob shu chatga keladi.",
        "ask_late_minutes": "⏰ Necha daqiqa kechikasiz? (masalan: 15)",
        "ask_late_reason": "✍️ Kechikish sababini yozing",
        "late_sent": "📨 Kechikish haqida xabar rahbarga yuborildi.",
        "request_approved": "✅ {date} uchun arizangiz <b>qabul qilindi</b> — jarima yo'q.\n{comment}",
        "request_rejected": "❌ {date} uchun arizangiz <b>rad etildi</b>.\n{comment}",
        "checkin_done": "✅ <b>{kind}</b> {time} belgisi qabul qilindi.",
        "checkin_not_allowed": "⚠️ Sizning ish rejimingiz uchun Telegram orqali belgilash mumkin emas — terminaldan foydalaning.",
        "invalid_phone": "⚠️ <b>«Telefonni ulashish»</b> tugmasini bosing 📱",
        "invalid_photo": "📷 Iltimos, rasm yuboring.",
        "empty_name": "⚠️ Ismingizni yozing.\n<i>Masalan: Sherzod yoki Sherzod Karimov</i>",
        "new_task": "📋 <b>Yangi vazifa</b>\n\n<b>{title}</b>\n{description}\n\n💰 Bonus: {bonus}\n\n«Qabul qilish» ni bosing, so'ng natijani yuboring (matn yoki rasm).",
        "task_result_ask": "✍️ <b>{title}</b> vazifasi natijasini yuboring: matn yoki rasm.",
        "task_result_sent": "📨 Natija tekshiruvga yuborildi.",
        "task_approved": "✅ <b>{title}</b> vazifasi tasdiqlandi. Bonus {bonus} hisoblandi.",
        "task_rejected": "❌ <b>{title}</b> vazifasi rad etildi.",
        "feed_pass": "{icon} <b>{full_name}</b>{position}\n🕐 {time} · {direction}{late}",
        "late_alert": "⏰ <b>Kechikish</b>\n👤 {full_name}{department}\n🕐 {time} da keldi (grafik {start}) — kechikish {late}",
        "absent_alert": "🚫 <b>Kelmaganlar</b> ({date}, {count} kishi)\n\n{list}",
        "hr_request": "📨 <b>Ariza: {kind}</b>\n👤 {full_name}{department}\n📅 {date}{late}\n💬 {reason}",
    },
}

BUTTONS = {
    "ru": {"register": "📝 Регистрация", "status": "📊 Статус", "hours": "⏱ Часы", "salary": "💰 Зарплата", "timesheet": "📄 Табель",
           "absence": "🚫 Не смогу прийти", "late": "⏰ Опаздываю", "checkin": "🟢 Пришёл", "checkout": "🔴 Ушёл", "lang": "🌐 Язык",
           "cancel": "❌ Отмена", "share_phone": "📱 Отправить телефон", "today": "Сегодня", "tomorrow": "Завтра", "no_photo": "Без фото",
           "accept": "✅ Принять", "reject": "❌ Отклонить", "accept_task": "✅ Принять задачу", "list": "📋 Список", "with_photo": "📷 С фото",
           "not_came": "🚫 Не пришли", "late_list": "⏰ Опоздали", "help": "📖 Помощь"},
    "uz": {"register": "📝 Ro'yxatdan o'tish", "status": "📊 Holat", "hours": "⏱ Soatlar", "salary": "💰 Maosh", "timesheet": "📄 Tabel",
           "absence": "🚫 Kela olmayman", "late": "⏰ Kechikyapman", "checkin": "🟢 Keldim", "checkout": "🔴 Ketdim", "lang": "🌐 Til",
           "cancel": "❌ Bekor", "share_phone": "📱 Telefonni ulashish", "today": "Bugun", "tomorrow": "Ertaga", "no_photo": "Rasmsiz",
           "accept": "✅ Qabul", "reject": "❌ Rad etish", "accept_task": "✅ Vazifani qabul qilish", "list": "📋 Ro'yxat", "with_photo": "📷 Rasm bilan",
           "not_came": "🚫 Kelmaganlar", "late_list": "⏰ Kechikkanlar", "help": "📖 Yordam"},
}

STATUS_LABELS = {
    "ru": {"on_time": "Вовремя", "late": "Опоздание", "early_leave": "Ранний уход", "late_early": "Опоздание и ранний уход", "absent": "Отсутствует",
           "excused": "Уваж. причина", "remote": "Удалённо", "worked_off": "Отработано", "leave": "Отпуск", "dismissed": "Уволен", "day_off": "Выходной",
           "holiday": "Праздник", "planned": "Запланировано", "not_hired": "—"},
    "uz": {"on_time": "O'z vaqtida", "late": "Kechikish", "early_leave": "Erta ketish", "late_early": "Kechikish va erta ketish", "absent": "Kelmagan",
           "excused": "Sababli", "remote": "Masofadan", "worked_off": "Ishlangan", "leave": "Ta'til", "dismissed": "Bo'shatilgan", "day_off": "Dam olish",
           "holiday": "Bayram", "planned": "Rejalashtirilgan", "not_hired": "—"},
}


def t(templates_override: dict | None, lang: str, key: str, **kwargs) -> str:
    base = TEMPLATES.get(lang, TEMPLATES["ru"])
    text = (templates_override or {}).get(key) or base.get(key) or TEMPLATES["ru"].get(key, key)
    try:
        return text.format(**kwargs)
    except (KeyError, IndexError):
        return text
